### Obter uma lista de produtos
GET http://localhost:5000/products


### Obter um produto pelo ID
GET http://localhost:5000/products/42


### Insetir um produto
 http://localhost:5000/products
Content-Type: application/json

{
    "teste": "teste_value"
}
