### Obter uma lista de produtos
GET http://localhost:5000/products


### Obter um produto pelo ID
GET http://localhost:5000/products/42


### Inserir um produto
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Computador",
    "description": "PC da Xuxa",
    "price": "1200.49",
    "stock": "1"
}

### Alterar um produto
PUT http://localhost:5000/products/42
Content-Type: application/json

{
    "price": "12.46"
}
